services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mynet
    container_name: "adminer"
    labels:
      - "nginx-proxy.host=adminer.local"
      - "nginx-proxy.port=8080"
      - "nginx-proxy.ssl=false"

networks:
  mynet:
    external: true