version: '3.4'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mynet
    container_name: "adminer"

networks:
  mynet:
    external: true