version: '3.4'

services:
  mynet:
    image: jwilder/nginx-proxy
    container_name: mynet
    ports:
    - "${HOST_PORT}:80"
    - "${HOST_PORT_SSL}:443"
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
    - mynet
    restart: always

networks:
  mynet:
    external: true