version: '3.4'

services:
  mynet:
    build:
      context: "${MYDOCK_ROOT}/utilities/proxy"
    container_name: mynet
    ports:
    - "${HOST_PORT}:80"
    - "${HOST_PORT_SSL}:443"
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - "${HOST_CERT_DIR}:/etc/nginx/certs"
    networks:
    - mynet
    restart: always

networks:
  mynet:
    external: true