services:
  web:
    image: joshlrogers/php7-apache
    working_dir: /usr/local/apache2/htdocs
    environment:
      - VIRTUAL_HOST=${PROJECT_DOMAIN}
    expose:
      - 80
    networks:
      - mynet
    container_name: "${PROJECT}"
    restart: always
    tty: true

networks:
  mynet:
    external: true