services:
  redis:
    image: joshlrogers/redis
    ports:
      - 6379:6379
    networks:
      - mynet
    container_name: "${PROJECT}"
    restart: always
    tty: true

networks:
  mynet:
    external: true
